require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/flavors", type: :request do
  
  # Flavor. As you add validations to Flavor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Flavor.create! valid_attributes
      get flavors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      flavor = Flavor.create! valid_attributes
      get flavor_url(flavor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_flavor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      flavor = Flavor.create! valid_attributes
      get edit_flavor_url(flavor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Flavor" do
        expect {
          post flavors_url, params: { flavor: valid_attributes }
        }.to change(Flavor, :count).by(1)
      end

      it "redirects to the created flavor" do
        post flavors_url, params: { flavor: valid_attributes }
        expect(response).to redirect_to(flavor_url(Flavor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Flavor" do
        expect {
          post flavors_url, params: { flavor: invalid_attributes }
        }.to change(Flavor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post flavors_url, params: { flavor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flavor" do
        flavor = Flavor.create! valid_attributes
        patch flavor_url(flavor), params: { flavor: new_attributes }
        flavor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the flavor" do
        flavor = Flavor.create! valid_attributes
        patch flavor_url(flavor), params: { flavor: new_attributes }
        flavor.reload
        expect(response).to redirect_to(flavor_url(flavor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        flavor = Flavor.create! valid_attributes
        patch flavor_url(flavor), params: { flavor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested flavor" do
      flavor = Flavor.create! valid_attributes
      expect {
        delete flavor_url(flavor)
      }.to change(Flavor, :count).by(-1)
    end

    it "redirects to the flavors list" do
      flavor = Flavor.create! valid_attributes
      delete flavor_url(flavor)
      expect(response).to redirect_to(flavors_url)
    end
  end
end
