require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/snacks", type: :request do
  
  # Snack. As you add validations to Snack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Snack.create! valid_attributes
      get snacks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      snack = Snack.create! valid_attributes
      get snack_url(snack)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_snack_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      snack = Snack.create! valid_attributes
      get edit_snack_url(snack)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Snack" do
        expect {
          post snacks_url, params: { snack: valid_attributes }
        }.to change(Snack, :count).by(1)
      end

      it "redirects to the created snack" do
        post snacks_url, params: { snack: valid_attributes }
        expect(response).to redirect_to(snack_url(Snack.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Snack" do
        expect {
          post snacks_url, params: { snack: invalid_attributes }
        }.to change(Snack, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post snacks_url, params: { snack: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested snack" do
        snack = Snack.create! valid_attributes
        patch snack_url(snack), params: { snack: new_attributes }
        snack.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the snack" do
        snack = Snack.create! valid_attributes
        patch snack_url(snack), params: { snack: new_attributes }
        snack.reload
        expect(response).to redirect_to(snack_url(snack))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        snack = Snack.create! valid_attributes
        patch snack_url(snack), params: { snack: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested snack" do
      snack = Snack.create! valid_attributes
      expect {
        delete snack_url(snack)
      }.to change(Snack, :count).by(-1)
    end

    it "redirects to the snacks list" do
      snack = Snack.create! valid_attributes
      delete snack_url(snack)
      expect(response).to redirect_to(snacks_url)
    end
  end
end
