require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/whiskeys", type: :request do
  
  # Whiskey. As you add validations to Whiskey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Whiskey.create! valid_attributes
      get whiskeys_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      whiskey = Whiskey.create! valid_attributes
      get whiskey_url(whiskey)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_whiskey_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      whiskey = Whiskey.create! valid_attributes
      get edit_whiskey_url(whiskey)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Whiskey" do
        expect {
          post whiskeys_url, params: { whiskey: valid_attributes }
        }.to change(Whiskey, :count).by(1)
      end

      it "redirects to the created whiskey" do
        post whiskeys_url, params: { whiskey: valid_attributes }
        expect(response).to redirect_to(whiskey_url(Whiskey.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Whiskey" do
        expect {
          post whiskeys_url, params: { whiskey: invalid_attributes }
        }.to change(Whiskey, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post whiskeys_url, params: { whiskey: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested whiskey" do
        whiskey = Whiskey.create! valid_attributes
        patch whiskey_url(whiskey), params: { whiskey: new_attributes }
        whiskey.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the whiskey" do
        whiskey = Whiskey.create! valid_attributes
        patch whiskey_url(whiskey), params: { whiskey: new_attributes }
        whiskey.reload
        expect(response).to redirect_to(whiskey_url(whiskey))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        whiskey = Whiskey.create! valid_attributes
        patch whiskey_url(whiskey), params: { whiskey: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested whiskey" do
      whiskey = Whiskey.create! valid_attributes
      expect {
        delete whiskey_url(whiskey)
      }.to change(Whiskey, :count).by(-1)
    end

    it "redirects to the whiskeys list" do
      whiskey = Whiskey.create! valid_attributes
      delete whiskey_url(whiskey)
      expect(response).to redirect_to(whiskeys_url)
    end
  end
end
