sorcery:
  twitter_callback_url: 'https://malt-mate.jp/oauth/callback?provider=twitter'
  google_callback_url: 'https://malt-mate.jp/oauth/callback?provider=google'
  line_callback_url: 'https://malt-mate.jp/oauth/callback?provider=line'
carrierwave:
  storage: :fog