sorcery:
  twitter_callback_url: 'https://whiskey-database-beta.herokuapp.com/oauth/callback?provider=twitter'
  google_callback_url: 'https://whiskey-database-beta.herokuapp.com/oauth/callback?provider=google'
  line_callback_url: 'https://whiskey-database-beta.herokuapp.com/oauth/callback?provider=line'
carrierwave:
  storage: :fog